/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import javax.swing.JOptionPane;

/**
 *
 * @author u11174571179
 */
public class JDlgApbClientes extends javax.swing.JDialog {

    /**
     * Creates new form JDlgApbClientes
     */
    public JDlgApbClientes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Clientes");
        setLocationRelativeTo(null);
        desabilitar();
    }
    public void habilitar(){
        jTxtApbCodigo.setEnabled(true);
        jTxtApbNome.setEnabled(true);
        jFmtApbCpf.setEnabled(true);
        jFmtApbDataNascimento.setEnabled(true);
        jTxtApbEmai.setEnabled(true);
        jTxtApbTelefone.setEnabled(true);
        jTxtApbEndereco.setEnabled(true);
        jTxtApbCidade.setEnabled(true);
        jFmtApbCep.setEnabled(true);
        jFmtApbUltimoLogin.setEnabled(true);
        jFmtApbDataCadastro.setEnabled(true);
        jFmtApbLimiteCredito.setEnabled(true);
        jCboApbGenero.setEnabled(true);
        jTxtApbClientePremium.setEnabled(true);
        jBtnApbConfirmar.setEnabled(true);
        jBtnApbCancelar.setEnabled(true);
        jBtnApbIncluir.setEnabled(false);
        jBtnApbAlterar.setEnabled(false);
        jBtnApbPesquisar.setEnabled(false);
        jBtnApbExcluir.setEnabled(false);
        
    }
    
    public void desabilitar(){
        jTxtApbCodigo.setEnabled(false);
        jTxtApbNome.setEnabled(false);
        jFmtApbCpf.setEnabled(false);
        jFmtApbDataNascimento.setEnabled(false);
        jTxtApbEmai.setEnabled(false);
        jTxtApbTelefone.setEnabled(false);
        jTxtApbEndereco.setEnabled(false);
        jTxtApbCidade.setEnabled(false);
        jFmtApbCep.setEnabled(false);
        jFmtApbUltimoLogin.setEnabled(false);
        jFmtApbDataCadastro.setEnabled(false);
        jFmtApbLimiteCredito.setEnabled(false);
        jCboApbGenero.setEnabled(false);
        jTxtApbClientePremium.setEnabled(false);
        jBtnApbConfirmar.setEnabled(false);
        jBtnApbCancelar.setEnabled(false);
        jBtnApbIncluir.setEnabled(true);
        jBtnApbAlterar.setEnabled(true);
        jBtnApbPesquisar.setEnabled(true);
        jBtnApbExcluir.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jLbApbCodigo = new javax.swing.JLabel();
        jTxtApbCodigo = new javax.swing.JTextField();
        jLbApbNome = new javax.swing.JLabel();
        jTxtApbNome = new javax.swing.JTextField();
        jLbApbCpf = new javax.swing.JLabel();
        jFmtApbCpf = new javax.swing.JFormattedTextField();
        jLbApbEmail = new javax.swing.JLabel();
        jTxtApbEmai = new javax.swing.JTextField();
        jLbApbTelefone = new javax.swing.JLabel();
        jTxtApbTelefone = new javax.swing.JTextField();
        jLbApbEndereco = new javax.swing.JLabel();
        jTxtApbEndereco = new javax.swing.JTextField();
        jLbAPbDataNascimento = new javax.swing.JLabel();
        jFmtApbDataNascimento = new javax.swing.JFormattedTextField();
        jLbApbCidade = new javax.swing.JLabel();
        jTxtApbCidade = new javax.swing.JTextField();
        jLbApbCep = new javax.swing.JLabel();
        jFmtApbCep = new javax.swing.JFormattedTextField();
        jFmtApbUltimoLogin = new javax.swing.JFormattedTextField();
        jLbApbUltimoLogin = new javax.swing.JLabel();
        jLbApbDataCadastro = new javax.swing.JLabel();
        jFmtApbDataCadastro = new javax.swing.JFormattedTextField();
        jlbApbLimiteCredito = new javax.swing.JLabel();
        jFmtApbLimiteCredito = new javax.swing.JFormattedTextField();
        jLbApbGenero = new javax.swing.JLabel();
        jCboApbGenero = new javax.swing.JComboBox<>();
        jLbApbClientePremium = new javax.swing.JLabel();
        jTxtApbClientePremium = new javax.swing.JTextField();
        jBtnApbIncluir = new javax.swing.JButton();
        jBtnApbAlterar = new javax.swing.JButton();
        jBtnApbExcluir = new javax.swing.JButton();
        jBtnApbConfirmar = new javax.swing.JButton();
        jBtnApbPesquisar = new javax.swing.JButton();
        jBtnApbCancelar = new javax.swing.JButton();

        jButton4.setText("jButton4");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLbApbCodigo.setText("Codigo");

        jTxtApbCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtApbCodigoActionPerformed(evt);
            }
        });

        jLbApbNome.setText("Nome");

        jTxtApbNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtApbNomeActionPerformed(evt);
            }
        });

        jLbApbCpf.setText("CPF");

        jFmtApbCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtApbCpfActionPerformed(evt);
            }
        });

        jLbApbEmail.setText("Email");

        jTxtApbEmai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtApbEmaiActionPerformed(evt);
            }
        });

        jLbApbTelefone.setText("Telefone");

        jTxtApbTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtApbTelefoneActionPerformed(evt);
            }
        });

        jLbApbEndereco.setText("Endereco");

        jLbAPbDataNascimento.setText("Data de Nascimento");

        jLbApbCidade.setText("Cidade");

        jTxtApbCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtApbCidadeActionPerformed(evt);
            }
        });

        jLbApbCep.setText("Cep");

        jFmtApbCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtApbCepActionPerformed(evt);
            }
        });

        jLbApbUltimoLogin.setText("Ultimo Login");

        jLbApbDataCadastro.setText("Data Cadastro ");

        jlbApbLimiteCredito.setText("Limite Credito");

        jLbApbGenero.setText("Genero");

        jCboApbGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCboApbGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCboApbGeneroActionPerformed(evt);
            }
        });

        jLbApbClientePremium.setText("Cliente Premium");

        jBtnApbIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir.png"))); // NOI18N
        jBtnApbIncluir.setText("Incluir");
        jBtnApbIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnApbIncluirActionPerformed(evt);
            }
        });

        jBtnApbAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.png"))); // NOI18N
        jBtnApbAlterar.setText("Alterar");
        jBtnApbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnApbAlterarActionPerformed(evt);
            }
        });

        jBtnApbExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir.png"))); // NOI18N
        jBtnApbExcluir.setText("Excluir");
        jBtnApbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnApbExcluirActionPerformed(evt);
            }
        });

        jBtnApbConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/confirmar.png"))); // NOI18N
        jBtnApbConfirmar.setText("Confirmar");
        jBtnApbConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnApbConfirmarActionPerformed(evt);
            }
        });

        jBtnApbPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        jBtnApbPesquisar.setText("Pesquisar");
        jBtnApbPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnApbPesquisarActionPerformed(evt);
            }
        });

        jBtnApbCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        jBtnApbCancelar.setText("Cancelar");
        jBtnApbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnApbCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnApbIncluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnApbAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnApbExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnApbConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnApbCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnApbPesquisar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTxtApbEmai, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtApbTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jTxtApbCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtApbNome, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTxtApbEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTxtApbCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLbApbCidade)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jFmtApbCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLbApbCpf)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLbAPbDataNascimento)
                                    .addComponent(jFmtApbDataNascimento)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(222, 222, 222)
                                .addComponent(jLbApbDataCadastro)
                                .addGap(35, 35, 35)
                                .addComponent(jlbApbLimiteCredito))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLbApbCodigo)
                                .addGap(50, 50, 50)
                                .addComponent(jLbApbNome))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLbApbEmail)
                                .addGap(106, 106, 106)
                                .addComponent(jLbApbTelefone)
                                .addGap(80, 80, 80)
                                .addComponent(jLbApbEndereco))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCboApbGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtApbClientePremium, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jFmtApbCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLbApbCep, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLbApbGenero))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLbApbClientePremium))
                                    .addComponent(jLbApbUltimoLogin)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jFmtApbUltimoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jFmtApbDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jFmtApbLimiteCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLbApbCodigo)
                            .addComponent(jLbApbNome)
                            .addComponent(jLbApbCpf)
                            .addComponent(jLbAPbDataNascimento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtApbNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFmtApbCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtApbCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFmtApbDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLbApbEmail)
                            .addComponent(jLbApbTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLbApbEndereco)
                            .addComponent(jLbApbCidade))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtApbCidade)
                        .addGap(2, 2, 2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtApbEmai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtApbTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtApbEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbApbCep)
                    .addComponent(jLbApbUltimoLogin)
                    .addComponent(jLbApbDataCadastro)
                    .addComponent(jlbApbLimiteCredito))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFmtApbCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtApbUltimoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtApbDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtApbLimiteCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbApbGenero)
                    .addComponent(jLbApbClientePremium))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCboApbGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtApbClientePremium, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnApbIncluir)
                    .addComponent(jBtnApbAlterar)
                    .addComponent(jBtnApbExcluir)
                    .addComponent(jBtnApbConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnApbPesquisar)
                    .addComponent(jBtnApbCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(122, 122, 122))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtApbNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtApbNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtApbNomeActionPerformed

    private void jFmtApbCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmtApbCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmtApbCpfActionPerformed

    private void jTxtApbCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtApbCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtApbCodigoActionPerformed

    private void jTxtApbEmaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtApbEmaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtApbEmaiActionPerformed

    private void jTxtApbTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtApbTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtApbTelefoneActionPerformed

    private void jCboApbGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCboApbGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCboApbGeneroActionPerformed

    private void jFmtApbCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmtApbCepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmtApbCepActionPerformed

    private void jBtnApbConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnApbConfirmarActionPerformed
        // TODO add your handling code here:
        desabilitar();
    }//GEN-LAST:event_jBtnApbConfirmarActionPerformed

    private void jBtnApbIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnApbIncluirActionPerformed
        // TODO add your handling code here:
        habilitar();
    }//GEN-LAST:event_jBtnApbIncluirActionPerformed

    private void jBtnApbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnApbAlterarActionPerformed
        // TODO add your handling code here:
        habilitar();
    }//GEN-LAST:event_jBtnApbAlterarActionPerformed

    private void jBtnApbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnApbExcluirActionPerformed
        // TODO add your handling code here:
        JOptionPane.showConfirmDialog(null, "Confirmar exclusão?", "selecione", JOptionPane.YES_NO_OPTION);
    }//GEN-LAST:event_jBtnApbExcluirActionPerformed

    private void jBtnApbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnApbCancelarActionPerformed
        // TODO add your handling code here:
        desabilitar();
    }//GEN-LAST:event_jBtnApbCancelarActionPerformed

    private void jBtnApbPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnApbPesquisarActionPerformed
        // TODO add your handling code here:
        JOptionPane.showInputDialog(null,"Entre com o codigo");
    }//GEN-LAST:event_jBtnApbPesquisarActionPerformed

    private void jTxtApbCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtApbCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtApbCidadeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgApbClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgApbClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgApbClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgApbClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgApbClientes dialog = new JDlgApbClientes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnApbAlterar;
    private javax.swing.JButton jBtnApbCancelar;
    private javax.swing.JButton jBtnApbConfirmar;
    private javax.swing.JButton jBtnApbExcluir;
    private javax.swing.JButton jBtnApbIncluir;
    private javax.swing.JButton jBtnApbPesquisar;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jCboApbGenero;
    private javax.swing.JFormattedTextField jFmtApbCep;
    private javax.swing.JFormattedTextField jFmtApbCpf;
    private javax.swing.JFormattedTextField jFmtApbDataCadastro;
    private javax.swing.JFormattedTextField jFmtApbDataNascimento;
    private javax.swing.JFormattedTextField jFmtApbLimiteCredito;
    private javax.swing.JFormattedTextField jFmtApbUltimoLogin;
    private javax.swing.JLabel jLbAPbDataNascimento;
    private javax.swing.JLabel jLbApbCep;
    private javax.swing.JLabel jLbApbCidade;
    private javax.swing.JLabel jLbApbClientePremium;
    private javax.swing.JLabel jLbApbCodigo;
    private javax.swing.JLabel jLbApbCpf;
    private javax.swing.JLabel jLbApbDataCadastro;
    private javax.swing.JLabel jLbApbEmail;
    private javax.swing.JLabel jLbApbEndereco;
    private javax.swing.JLabel jLbApbGenero;
    private javax.swing.JLabel jLbApbNome;
    private javax.swing.JLabel jLbApbTelefone;
    private javax.swing.JLabel jLbApbUltimoLogin;
    private javax.swing.JTextField jTxtApbCidade;
    private javax.swing.JTextField jTxtApbClientePremium;
    private javax.swing.JTextField jTxtApbCodigo;
    private javax.swing.JTextField jTxtApbEmai;
    private javax.swing.JTextField jTxtApbEndereco;
    private javax.swing.JTextField jTxtApbNome;
    private javax.swing.JTextField jTxtApbTelefone;
    private javax.swing.JLabel jlbApbLimiteCredito;
    // End of variables declaration//GEN-END:variables
}
