/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author u11174571179
 */
public class JFrmApbMenu extends javax.swing.JFrame {

    /**
     * Creates new form JFrmApbMenu
     */
    public JFrmApbMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMnuApbProdutos = new javax.swing.JMenu();
        jMnuApbFornecedor = new javax.swing.JMenuItem();
        jMnuApbClientes = new javax.swing.JMenuItem();
        jMnuApbUsuarios = new javax.swing.JMenuItem();
        jMnuApbVendedor = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMnuApbSair = new javax.swing.JMenuItem();
        jMnuApbMovimentos = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMnuApbProdutos.setText("Cadastro");

        jMnuApbFornecedor.setText("Fornedor");
        jMnuApbFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuApbFornecedorActionPerformed(evt);
            }
        });
        jMnuApbProdutos.add(jMnuApbFornecedor);

        jMnuApbClientes.setText("Clientes");
        jMnuApbClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuApbClientesActionPerformed(evt);
            }
        });
        jMnuApbProdutos.add(jMnuApbClientes);

        jMnuApbUsuarios.setText("Usuarios");
        jMnuApbUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuApbUsuariosActionPerformed(evt);
            }
        });
        jMnuApbProdutos.add(jMnuApbUsuarios);

        jMnuApbVendedor.setText("Vendedor");
        jMnuApbVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuApbVendedorActionPerformed(evt);
            }
        });
        jMnuApbProdutos.add(jMnuApbVendedor);

        jMenuItem1.setText("Produtos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMnuApbProdutos.add(jMenuItem1);
        jMnuApbProdutos.add(jSeparator6);

        jMnuApbSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/exit.png"))); // NOI18N
        jMnuApbSair.setText("Sair");
        jMnuApbSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuApbSairActionPerformed(evt);
            }
        });
        jMnuApbProdutos.add(jMnuApbSair);

        jMenuBar2.add(jMnuApbProdutos);

        jMnuApbMovimentos.setText("Movimentos");

        jMenuItem2.setText("Compras");
        jMnuApbMovimentos.add(jMenuItem2);

        jMenuItem3.setText("Produtos");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMnuApbMovimentos.add(jMenuItem3);

        jMenuBar2.add(jMnuApbMovimentos);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMnuApbVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuApbVendedorActionPerformed
        // TODO add your handling code here:
        JDlgApbVendedor jDlgApbVendedor = new JDlgApbVendedor(null, true);
        jDlgApbVendedor.setVisible(true);
    }//GEN-LAST:event_jMnuApbVendedorActionPerformed

    private void jMnuApbUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuApbUsuariosActionPerformed
        // TODO add your handling code here:
        JDlgApbUsuarios jDlgApbUsuarios = new JDlgApbUsuarios(null, true);
        jDlgApbUsuarios.setVisible(true);
    }//GEN-LAST:event_jMnuApbUsuariosActionPerformed

    private void jMnuApbClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuApbClientesActionPerformed
        // TODO add your handling code here:
        JDlgApbClientes jDlgApbClientes = new JDlgApbClientes(null, true);
        jDlgApbClientes.setVisible(true);
    }//GEN-LAST:event_jMnuApbClientesActionPerformed

    private void jMnuApbFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuApbFornecedorActionPerformed
        // TODO add your handling code here:
        JDlgApbFornecedor jDlgApbFornecedor = new JDlgApbFornecedor(null, true);
        jDlgApbFornecedor.setVisible(true);
    }//GEN-LAST:event_jMnuApbFornecedorActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        JDlgProdutos jDlgProdutos = new JDlgProdutos(null, true);
        jDlgProdutos.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMnuApbSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuApbSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMnuApbSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmApbMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmApbMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmApbMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmApbMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmApbMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMnuApbClientes;
    private javax.swing.JMenuItem jMnuApbFornecedor;
    private javax.swing.JMenu jMnuApbMovimentos;
    private javax.swing.JMenu jMnuApbProdutos;
    private javax.swing.JMenuItem jMnuApbSair;
    private javax.swing.JMenuItem jMnuApbUsuarios;
    private javax.swing.JMenuItem jMnuApbVendedor;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    // End of variables declaration//GEN-END:variables
}
